apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: quay.io/ukhomeofficedigital/mysql:v0.5.1
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 400m
            memory: 800Mi
          requests:
            cpu: 400m
            memory: 800Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 
        - name: MYSQL_DATABASE
          value: hello
        - name: MYSQL_USER
          value: hello
        - name: MYSQL_PASSWORD
          value:
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        emptyDir: {}
