apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-workd4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world4
    spec:
      containers:
      - name: node
        image: quay.io/ukhomeofficedigital/node-hello-world-4:0c796f6b57b4457acdff71b84c809001952a0e10
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
        ports:
        - name: https
          containerPort: 443
          protocol: TCP
